name: Main CI Workflow

on:
  pull_request:
  push:

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node:
          - 16
          - 18
          - 19
          - 20

        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install prerequisites
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
